### ISSUE TITLE
Coverage from AMIS not being applied

### ISSUE THREAD

**Issue by RaihaTuiTaura** [NTD-Modelling-Consortium/trachoma-amis-integration#14]
I'm working on the branch `moveDependencyToMain` and I'm not sure the coverage provided by AMIS is correctly overwriting whatever is provided in the CSV files that specify MDA years. When using the attached CSV as input (where I just set "coverage" = 1) I'm getting this error: 

<img width="1512" alt="Screenshot 2024-08-30 at 20 11 06" src="https://github.com/user-attachments/assets/a7a8df73-04d2-417c-a30d-f03b98062cfd">

I believe this is because the `drawTreatmentProbabilities` function is trying to draw random Beta variables with b=0, which is invalid.

This indicates to me that the `cov` argument to`drawTreatmentProbabilities` is still equal to 1, and hasn't been overwritten by the coverage provided from AMIS. To confirm this, I changed the coverage values in the CSV to something below 1 and it all ran without error. 

[InputMDA_MTP_349.csv](https://github.com/user-attachments/files/16821444/InputMDA_MTP_349.csv)

**Comment by thk123** [comment]
Yup I'm not sure why I didn't spot this before, it will end up using the right coverage value as these initial values are thrown away if the coverage changes, but we should use the right values from the get go - I'll raise a PR addressing this today.

**Comment by thk123** [comment]
I've pushed a fix for this to the main branch - I can't test it as the coverage file is actually hard coded - will raise an issue to address this.
