### ISSUE TITLE
Missing argument 'numpy_state' in Set_inits()

### ISSUE THREAD

**Issue by RaihaTuiTaura** [NTD-Modelling-Consortium/trachoma-amis-integration#4]
Error message below when running trachoma_fitting.R. I think the amis integration package is based on an older version of the trachoma code, `Set_inits()` function now requires argument `numpy_state`

> source("trachoma_fitting.R")
Error in py_call_impl(callable, call_args$unnamed, call_args$named) : 
  TypeError: Set_inits() missing 1 required positional argument: 'numpy_state'
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ───────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/Users/u2176058/Documents/trachoma-endgame/trachoma-amis-integration/trachoma_amis/amis_integration.py", line 103, in build_transmission_model
    ) = setup(initial_infect_frac)
  File "/Users/u2176058/Documents/trachoma-endgame/trachoma-amis-integration/trachoma_amis/amis_integration.py", line 50, in setup
    vals = Set_inits(parameters, demog, sim_params)
TypeError: Set_inits() missing 1 required positional argument: 'numpy_state'

── R Traceback ────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. ├─base::source("trachoma_fitting.R")
 2. │ ├─base::withVisible(eval(ei, envir))
 3. │ └─base::eval(ei, envir)
 4. │   └─base::eval(ei, envir)
 5. └─amis_int_mod$build_transmission_model(...) at trachoma_fitting.R:30:1
 6.   └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)

**Comment by tlestang** [comment]
That's right, this is based on version 1.0.0 (the latest tag) of the trachoma model

**Comment by RaihaTuiTaura** [comment]
Thanks Thibault - I rolled back to v1.0.0 (noting required downgrading NumPy from 2.0.1 to 1.26.4 and adding version tag to trachoma package in `pyproject.toml`). But now getting the error below.

p.s. sorry for the many questions - I saw that you were going to look at the integration later this week so I can stop here until you've had a chance to do this

```
Exception type IndexError was raised during the execution of the model:

── Python Exception Message ─────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/Users/u2176058/Documents/trachoma-endgame/trachoma-amis-integration/trachoma_amis/amis_integration.py", line 114, in run_trachoma
    results = Parallel(n_jobs=num_cores)(
  File "/Users/u2176058/Documents/trachoma-endgame/trachoma-venv/lib/python3.10/site-packages/joblib/parallel.py", line 1918, in __call__
    return output if self.return_generator else list(output)
  File "/Users/u2176058/Documents/trachoma-endgame/trachoma-venv/lib/python3.10/site-packages/joblib/parallel.py", line 1847, in _get_sequential_output
    res = func(*args, **kwargs)
  File "/Users/u2176058/Documents/trachoma-endgame/trachoma-venv/lib/python3.10/site-packages/trachoma/trachoma_functions.py", line 1184, in run_single_simulation
    results = sim_Ind_MDA_Include_Survey(params=params, Tx_mat = Tx_mat,
  File "/Users/u2176058/Documents/trachoma-endgame/trachoma-venv/lib/python3.10/site-packages/trachoma/trachoma_functions.py", line 919, in sim_Ind_MDA_Include_Survey
    vals = stepF_fixed(vals=vals, params=params, demog=demog, bet=betas[i])
  File "/Users/u2176058/Documents/trachoma-endgame/trachoma-venv/lib/python3.10/site-packages/trachoma/trachoma_functions.py", line 155, in stepF_fixed
    lambda_step = 1 - np.exp(- getlambdaStep(params=params, Age=vals['Age'], bact_load=vals['bact_load'],
  File "/Users/u2176058/Documents/trachoma-endgame/trachoma-venv/lib/python3.10/site-packages/trachoma/trachoma_functions.py", line 310, in getlambdaStep
    returned[vaccinated] = (1 - prob_reduction[vaccinated]) * returned[vaccinated]
IndexError: arrays used as indices must be of integer (or boolean) type

── R Traceback ──────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─AMISforInfectiousDiseases::amis(...)
 2.   └─global transmission_model(seeds = 1:n_samples, param, n_tims) at evandrokonzen-AMISforInfectiousDiseases-dev-55f99ef/R/AMIS.R:270:5
 3.     ├─base::tryCatch(...)
 4.     │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 5.     │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 6.     │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
 7.     └─reticulate (local) model_func(seeds, params, n_tims)
 8.       └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named)
Error in value[[3L]](cond) : 
  list(AMISforInfectiousDiseases::amis(prevalence_map, function(seeds, params, n_tims) {
    tryCatch(expr = {
        model_func(seeds, params, n_tims)
    }, error = error_function)
}, prior), transmission_model(seeds = 1:n_samples, param, n_tims), tryCatch(expr = {
    model_func(seeds, params, n_tims)
}, error = error_function), tryCatchList(expr, classes, parentenv, handlers), tryCatchOne(expr, names, parentenv, handlers[[1]]), doTryCatch(return(expr), name, parentenv, handler), model_func(seeds, params, n_tims), py_call_impl(callable, call_args$unnamed, call_args$named))c(0, 1, 2, 3, 4, 5, 2, 7)c(TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE)c("AMISforInfectiousDiseases", NA, "base", "base", "base", "base", "reticulate", "reticulate")c("::", "global", "::", "local", "local", "local", "local", ":::")list(AMISforInfectiousDiseases::amis(prevalence_map, function(seeds, params, n_tims) {
    tryCatch(expr = {
        model_func(seeds, params, n_tims)
    }, error = error_func

```

**Comment by tlestang** [comment]
Yes, I'm getting this one as well and I don't have a fix for it at the moment. It looks like vaccination isn't setup correctly in amis_integration.py. I'm not going to be able to get a close look to this before friday I'm afraid.
